#----------------- base param -----------------#
simulation:    false
perfect_simu:  false
mass:          2.4 # kg
gra:           9.81 
ctrl_freq_max: 100.0
max_manual_vel: 4.0
low_voltage:   13.2 # 4S battery

ctrl_delay:    0.0

thrust_limit:  0.99
hover_esti:    true
hover_perc:    0.50

visualization_en: false
corridor_bound_dis: 5.0
corridor_line_max_length: 5.0
visual_process: false
frontend_in_known_free: false
iris_iter_num: 4  #迭代次数越多，走廊越“宽松”，但计算量也增加
obs_skip_num: 2   #障碍物采样跳步数。生成安全走廊时，障碍物点云会进行下采样，跳过部分点以减少计算量。
robot_r: 0.1
ref_dis:     5   #ref_dis为MPC参考点间距间的点个数，表示ref_dis个点的距离作为MPC在horizon内的一个目标点，因此MPC间隔间距为ref_dis * path_dis
path_dis:    0.02  #路径稠密化的插值间距 5cm

yaw_ctrl_flag:  true
yaw_gain:       3.5
yaw_ki:         0.05
yaw_i_limit:    0.5
yaw_rate_limit: 5.0

goal_x:        0.0
goal_y:        0.0
goal_z:        1.5

rc_reverse: # *
    roll: false
    pitch: false
    yaw: false
    throttle: true

auto_takeoff_land:
    enable: true #set false when use qgc takeoff 
    enable_auto_arm: true
    no_RC: true # set true when sim, set false in exp
    takeoff_height: 1.5 # m
    takeoff_land_speed: 0.3 # m/s


rog_astar:
  map_voxel_num: [ 500, 500, 10 ]  # 乘以resolution 0.2 得到实际体积大小
  visual_process: false
  allow_diag: true
  # 0 DIAG; 1 MANHATTAN; 2 EUCLIDEAN
  heu_type: 0
  debug_visualization_en: false
  # path_dis:    0.02  #floyd路径稠密化的插值间距 2cm

mpc:
  horizon:     15 #总的预测步数，总的预测距离为 horizon * ref_dis * path_dis  要在box内
  step:        0.1
  # ctrl_delay:  0   # n step

  R_p:         2000.0
  R_v:         200.0
  R_a:         0.0
  R_u:         1  #控制量惩罚项权重，
  R_u_con:     1  #平滑度惩罚项，防止控制量跳变过大
  R_pN:        2000.0
  R_vN:        200.0
  R_aN:        200.0

  D_x:         0.0
  D_y:         0.0
  D_z:         0.0

  vx_min:     -20.0
  vy_min:     -20.0
  vz_min:     -10.0
  vx_max:      20.0
  vy_max:      20.0
  vz_max:      10.0

  ax_min:     -15.0
  ay_min:     -15.0
  az_min:     -10.0
  ax_max:      15.0
  ay_max:      15.0
  az_max:      10.0

  ux_min:     -150.0
  uy_min:     -150.0
  uz_min:     -150.0
  ux_max:      150.0
  uy_max:      150.0
  uz_max:      150.0


rog_map:
  resolution: 0.3
  inflation_resolution: 0.3
  inflation_step: 2         
  unk_inflation_en: true
  unk_inflation_step: 1
  map_size: [ 50, 50, 5 ]
  # If the map rolling is disable, the map origin [m] should be set.
  fix_map_origin: [ 0,0, 0.5 ] #会限制A*搜索的高度，但不会限制安全飞行走廊
  frontier_extraction_en: false

  # Virtual ceil and ground
  virtual_ceil_height: 5
  virtual_ground_height: -0.5

  load_pcd_en: false

  map_sliding:
    enable: true
    # The minimum distance [m] to slide the map.
    threshold: 0.4

  esdf:
    enable: false
    resolution: 0.1
    # The range of esdf around the odom [m].
    local_update_box: [ 5,5,4 ]

  # If [enable = true], the ROG-Map will actively take ros topic as input.
  #  else user should call function [updateMap] to update the map.
  ros_callback:
    enable: true
    cloud_topic: "/cloud_registered"
    odom_topic: "/mavros/local_position/odom"
    odom_timeout: 2.0


  visualization:
    enable: true
    # when enabled, use rqt_reconfigure to change the visualization parameters.
    use_dynamic_reconfigure: false
    # The rate of visualization [Hz], if set to 0, the visualization will not be triggered by frame.
    time_rate: 2
    # The frame rate of visualization [Hz], if set to 0, the visualization will not be triggered by frame.
    frame_rate: 0
    # visualization range along the odom [m].
    range: [ 50, 50,10 ]
    frame_id: "map"
    pub_unknown_map_en: false

  # Intensity filter for input point cloud. If the point intensity is less than this value,
  # it will be ignored (to avoid noise like dusk).
  intensity_thresh: -10
  # The temporal downsample rate for input point cloud.
  #  e.g. if set to k, the point cloud will be downsampled to 1/k.
  point_filt_num: 1

  # Probabilistc update
  raycasting:
    # if disable, the map will only maintain occupied information, and all other grid
    # will be considered as unknown.
    enable: disable
    batch_update_size: 1
    local_update_box: [ 100,100,5 ]
    # The range of raycasting [m].
    ray_range: [0.5, 100 ]

    p_min: 0.12
    p_miss: 0.49
    p_free: 0.499
    p_occ: 0.85
    p_hit: 0.9
    p_max: 0.98
    # The threshold of a non-occupied inf map grid to be considered as free. [0.0-1.0]
    # for counter map, if each cell contains N cells in prob map, then only when
    # N_unk > N * unk_thresh cells are unknown, the cell will be considered as unknown.
    # example: 1) if unk_thresh is set 0.0, then once at least one cell in prob map is unknown,
    #             the cell will be considered as unknown.
    #         2) if unk_thresh is set to 1.0, then only all cells in prob map are unknown,
    #             the cell will be considered as unknown.
    # in all, 1.0 is more aggressive while 0.0 is more conservative.
    unk_thresh: 1.0


msg_timeout:
    odom: 0.5
    rc:   0.5
    cmd:  0.5
    imu:  0.5
    bat:  0.5
    goal: 0.5